wip

diff --git a/preseed/ubuntu/minion-setup b/preseed/ubuntu/minion-setup
--- a/preseed/ubuntu/minion-setup
+++ b/preseed/ubuntu/minion-setup
@@ -3,6 +3,38 @@
 # meant to be run via systemd on a vbox minion
 # an easier way to deploy since salt-cloud doesn't work
 
+function comment() {
+# I have seen a few instances where this error popped up:
+
+# VBoxControl: error: Could not contact the host system.  Make sure that you are running this
+# VBoxControl: error: application inside a VirtualBox guest system, and that you have sufficient
+# VBoxControl: error: user permissions.
+
+# It looks like the script is running just a few seconds before the kernel module is loaded.
+# This loop should fix that.
+
+retval=1
+attempt=0
+maxattempts=10
+while [ ${retval} -eq 1 ]; do 
+  dmesg | grep -q 'vboxguest: Successfully loaded'
+  if [ $? -eq 0 ]; then
+    echo "vboxguest kernel module loaded, proceeding..."
+    break
+  else
+    let attempt+=1
+    if [ ${attempt} -ge ${maxattempts} ]; then
+      echo "ERROR: vboxguest kernel module is not loaded - waited 10 seconds. Exiting."
+      exit 255
+    else
+      echo "vboxguest kernel module has not loaded, sleeping..."
+      sleep 1
+    fi
+  fi
+done
+}
+
+# get the new hostname
 newHostName=$(VBoxControl --nologo guestproperty get GuestName | awk '{ print $2 }')
 
 # make sure the result isn't zero length (indicating VBoxControl doesn't work), or "value" (not set)
@@ -24,7 +56,10 @@ echo ${newHostName}.lab > /etc/salt/minion_id
 echo "master: 10.187.88.10" | tee /etc/salt/minion
 
 # regenerate UUID, otherwise Ubuntu acts totally stupid
-rm -f /etc/machine-id && dbus-uuidgen --ensure=/etc/machine-id
+if [ -f /etc/machine-id ]; then
+  # required for ubuntu 18.04
+  rm -f /etc/machine-id && dbus-uuidgen --ensure=/etc/machine-id
+fi
 
 # start Salt minion next boot
 systemctl enable salt-minion
